### ISSUE TITLE
Freezes browser on big tank suicide O and on die by player

### ISSUE THREAD

**Issue by murchalkin** [ABCxFF/diepcustom#53]

**Comment by n0deee** [comment]
the report is not very descriptive. could you add more information please? if possible, follow this model:


**What is inconsistent**
A clear and concise description of what the bug is. Describe if the bug is missing in diepcustom, or if it is just improperly implemented.

**Expected behavior**
If known, provide a clear and concise description of what should be expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your findings.

**Additional notes**
Add any other context about the inconsistency here.

**Comment by murchalkin** [comment]
Just my server is disabling when i die with 500 level

**Comment by Nul-led** [comment]
Known issue caused by a couple of factors
a) Writer Capacity Limit
b) Websocket Packet Capacity Limit
c) Server resources (large entities are costly because of collisions etc)

**Comment by Nul-led** [comment]
Should be fixed with new write stream
